# Generated by Django 4.1 on 2022-09-08 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('tipo_documento', models.CharField(max_length=10)),
                ('numero_documento', models.CharField(max_length=15)),
                ('correo_electronico', models.CharField(max_length=50)),
                ('clave', models.CharField(max_length=30)),
                ('tipo_usuario', models.CharField(max_length=20)),
                ('usuario_nuevo', models.BooleanField()),
            ],
        ),
    ]
