# Generated by Django 4.1 on 2022-09-12 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='tipo_documento',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='tipo_usuario',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='usuario_nuevo',
        ),
    ]
