# Generated by Django 4.1 on 2022-09-12 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='hora_entrada',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='hora_salida',
        ),
    ]
